import Head from 'next/head';

import { Button, Htag, Input, P, Rating, Tag, Textarea } from '@/components';
import { useState } from 'react';
import { Layout, withLayout } from '@/layout/Layout';
import { GetStaticProps } from 'next';
import axios from 'axios';
import { MenuItem } from '@/interfaces/menu.interface';
import { API } from '../../helpers/api';

function Home({ menu }: HomeProps): JSX.Element {
    const [rating, setRating] = useState<number>(4);
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                {/* <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link
                    href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@300;400;500;700&family=Rubik:wght@400;500;600;700&display=swap"
                    rel="stylesheet"
                /> */}
            </Head>

            <>
                <Htag tag="h1">Текст</Htag>
                <Button appearance="primary" arrow="right">
                    Кнопка
                </Button>
                <Button appearance="ghost" arrow="right">
                    Кнопка
                </Button>

                <P size="l">Большой</P>
                <P>Средний</P>
                <P size="s">Маленький</P>
                <Tag size="s">Тест</Tag>
                <Rating rating={rating} isEditable setRating={setRating} />
                <Input placeholder="тест" />
                <Textarea placeholder="test area" />
            </>
        </>
    );
}

export default withLayout(Home);

export const getStaticProps: GetStaticProps<HomeProps> = async () => {
    const firstCategory = 0;
    const { data: menu } = await axios.post<MenuItem[]>(API.topPage.find, {
        firstCategory,
    });
    return {
        props: {
            menu,
            firstCategory,
        },
    };
};

interface HomeProps extends Record<string, unknown> {
    menu: MenuItem[];
    firstCategory: number;
}
